module.exports = [

    { country: "Abu Dhabi", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Afghanistan", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Albania", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Algeria", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "American Samoa", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Andorra", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Angola", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Anguilla", voltage: "120/208 V / 127/220 V / 240/415 V", frequency: "60", phase: "3, 4" },
    { country: "Antigua and Barbuda", voltage: "400 V", frequency: "60", phase: "3, 4" },
    { country: "Argentina", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Armenia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Aruba", voltage: "220 V", frequency: "60", phase: "3, 4" },
    { country: "Australia", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Austria", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Azerbaijan", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Azores", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Bahamas", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Bahrain", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Balearic Islands", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Bangladesh", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Barbados", voltage: "200 V", frequency: "50", phase: "3, 4" },
    { country: "Belarus", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Belgium", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Belize", voltage: "190 V / 380 V", frequency: "60", phase: "3, 4" },
    { country: "Benin", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Bermuda", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Bhutan", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Bolivia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Bonaire", voltage: "220 V", frequency: "50", phase: "3, 4" },
    { country: "Bosnia & Herzegovina", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Botswana", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Brazil", voltage: "220 V / 380 V", frequency: "60", phase: "3, 4" },
    { country: "British Virgin Islands", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Brunei", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Bulgaria", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Burkina Faso", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Burma (officially Myanmar)", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Burundi", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Cambodia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Cameroon", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Canada", voltage: "120/208 V / 240 V / 480 V / 347/600 V", frequency: "60", phase: "3, 4" },
    { country: "Canary Islands", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Cape Verde", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Cayman Islands", voltage: "240 V", frequency: "60", phase: "3" },
    { country: "Central African Republic", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Chad", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Channel Islands (Guernsey & Jersey)", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Chile", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "China, People’s Republic of", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Colombia", voltage: "220 V / 440 V", frequency: "60", phase: "3, 4" },
    { country: "Comoros", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Congo, Democratic Republic of", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Congo, People’s Republic of", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Cook Islands", voltage: "415 V", frequency: "50", phase: "3, 4" },
    { country: "Costa Rica", voltage: "240 V", frequency: "60", phase: "3, 4" },
    { country: "Côte d’Ivoire (Ivory Coast)", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Croatia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Cuba", voltage: "190 V", frequency: "60", phase: "3" },
    { country: "Curaçao", voltage: "220 V / 380 V", frequency: "50", phase: "3, 4" },
    { country: "Cyprus", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Czech Republic", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Denmark", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Djibouti", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Dominica", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Dominican Republic", voltage: "120/208 V / 277/480 V", frequency: "60", phase: "3, 4" },
    { country: "Dubai", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "East Timor (Timor-Leste)", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Ecuador", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Egypt", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "El Salvador", voltage: "200 V", frequency: "60", phase: "3" },
    { country: "England", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Equatorial Guinea", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Eritrea", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Estonia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Ethiopia", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Faeroe Islands", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Falkland Islands", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Fiji", voltage: "415 V", frequency: "50", phase: "3, 4" },
    { country: "Finland", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "France", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "French Guiana", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Gabon (Gabonese Republic)", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Gambia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Gaza", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Georgia", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Germany", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Ghana", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Gibraltar", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Great Britain (GB)", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Greece", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Greenland", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Grenada", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Guadeloupe", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Guam", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Guatemala", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Guinea", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Guinea-Bissau", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Guyana", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Haiti", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Holland (officially the Netherlands)", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Honduras", voltage: "208 V / 230 V / 240 V / 460 V / 480 V", frequency: "60", phase: "3, 4" },
    { country: "Hong Kong", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Hungary", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Iceland", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "India", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Indonesia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Iran", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Iraq", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Ireland (Eire)", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Ireland, Northern", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Isle of Man", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Israel", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Italy", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Jamaica", voltage: "190 V", frequency: "50", phase: "3, 4" },
    { country: "Japan", voltage: "200 V", frequency: "5060", phase: "3" },
    { country: "Jordan", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Kazakhstan", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Kenya", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Kiribati", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Korea, North", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Korea, South", voltage: "380 V", frequency: "60", phase: "4" },
    { country: "Kosovo", voltage: "230 V / 400 V", frequency: "50", phase: "3" },
    { country: "Kuwait", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Kyrgyzstan", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Laos", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Latvia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Lebanon", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Lesotho", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Liberia", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Libya", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Liechtenstein", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Lithuania", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Luxembourg", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Macau", voltage: "380 V", frequency: "50", phase: "3" },
    { country: "Macedonia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Madagascar", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Madeira", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Malawi", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Malaysia", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Maldives", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Mali", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Malta", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Marshall Islands", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Martinique", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Mauritania", voltage: "220 V", frequency: "50", phase: "3, 4" },
    { country: "Mauritius", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Mayotte", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Mexico", voltage: "220 V / 480 V", frequency: "60", phase: "3, 4" },
    { country: "Micronesia, Federated States of", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Moldova", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Monaco", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Mongolia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Montenegro", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Montserrat", voltage: "400 V", frequency: "60", phase: "4" },
    { country: "Morocco", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Mozambique", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Myanmar (formerly Burma)", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Namibia", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Nauru", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Nepal", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Netherlands", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "New Caledonia", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "New Zealand", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Nicaragua", voltage: "208 V", frequency: "60", phase: "3, 4" },
    { country: "Niger", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Nigeria", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Northern Ireland", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "North Korea", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Norway", voltage: "230 V / 400 V", frequency: "50", phase: "3, 4" },
    { country: "Oman", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Pakistan", voltage: "400 V", frequency: "50", phase: "3" },
    { country: "Palau", voltage: "208 V", frequency: "60", phase: "3" },
    { country: "Panama", voltage: "240 V", frequency: "60", phase: "3" },
    { country: "Papua New Guinea", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Paraguay", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Peru", voltage: "220 V", frequency: "60", phase: "3" },
    { country: "Philippines", voltage: "380 V", frequency: "60", phase: "3" },
    { country: "Pitcairn Islands", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Poland", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Portugal", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Puerto Rico", voltage: "480 V", frequency: "60", phase: "3, 4" },
    { country: "Qatar", voltage: "415 V", frequency: "50", phase: "3, 4" },
    { country: "Réunion", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Romania", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Russia (officially the Russian Federation)", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Rwanda", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Saba", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Saint Kitts and Nevis (officially the Federation of Saint Christopher and Nevis)", voltage: "400 V", frequency: "60", phase: "4" },
    { country: "Saint Lucia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Saint Martin", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Saint Helena", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Sint Eustatius", voltage: "220 V", frequency: "60", phase: "3, 4" },
    { country: "Sint Maarten", voltage: "220 V", frequency: "60", phase: "3, 4" },
    { country: "Saint Vincent and the Grenadines", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Samoa", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "San Marino", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "São Tomé and Príncipe", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Saudi Arabia", voltage: "400 V", frequency: "60", phase: "4" },
    { country: "Scotland", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Senegal", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Serbia", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Seychelles", voltage: "240 V", frequency: "50", phase: "3" },
    { country: "Sierra Leone", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Singapore", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Slovakia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Slovenia", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Solomon Islands", voltage: "[unavailable]", frequency: "", phase: "[unavailable]" },
    { country: "Somalia", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "Somaliland", voltage: "380 V", frequency: "50", phase: "3, 4" },
    { country: "South Africa", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "South Korea", voltage: "380 V", frequency: "60", phase: "4" },
    { country: "South Sudan", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Spain", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Sri Lanka", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Sudan", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Suriname", voltage: "220 V / 400 V", frequency: "60", phase: "3, 4" },
    { country: "Swaziland", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Sweden", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Switzerland", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Syria", voltage: "380 V", frequency: "50", phase: "3" },
    { country: "Tahiti", voltage: "380 V", frequency: "5060", phase: "3, 4" },
    { country: "Taiwan", voltage: "220 V", frequency: "60", phase: "4" },
    { country: "Tajikistan", voltage: "380 V", frequency: "50", phase: "3" },
    { country: "Tanzania", voltage: "415 V", frequency: "50", phase: "3, 4" },
    { country: "Thailand", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Togo", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Tonga", voltage: "415 V", frequency: "50", phase: "3, 4" },
    { country: "Trinidad & Tobago", voltage: "115/230 V / 230/400 V", frequency: "60", phase: "4" },
    { country: "Tunisia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Turkey", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Turkmenistan", voltage: "380 V", frequency: "50", phase: "3" },
    { country: "Turks and Caicos Islands", voltage: "240 V", frequency: "60", phase: "4" },
    { country: "Uganda", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Ukraine", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "United Arab Emirates (UAE)", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "United Kingdom (UK)", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "United States of America (USA)", voltage: "120/208 V / 277/480 V / 120/240 V / 240 V / 480 V", frequency: "60", phase: "3, 4" },
    { country: "United States Virgin Islands", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Uruguay", voltage: "380 V", frequency: "50", phase: "3" },
    { country: "Uzbekistan", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Vanuatu", voltage: "400 V", frequency: "50", phase: "3, 4" },
    { country: "Venezuela", voltage: "120 V", frequency: "60", phase: "3, 4" },
    { country: "Vietnam", voltage: "380 V", frequency: "50", phase: "4" },
    { country: "Virgin Islands (British)", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Virgin Islands (USA)", voltage: "190 V", frequency: "60", phase: "3, 4" },
    { country: "Wales", voltage: "415 V", frequency: "50", phase: "4" },
    { country: "Yemen", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Zambia", voltage: "400 V", frequency: "50", phase: "4" },
    { country: "Zimbabwe", voltage: "415 V", frequency: "50", phase: "3, 4" },

]
